on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Before '
        run: ls

      - user: actions/checkout@v3

      - name: 'After'
        run: ls