on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3

      - name: " login to dockerhub"
        run: docker login --username ${{ secrets.DOKER_NAME}} --password ${{ secrets.DOKER_TOKEN }}
      - name: " building docker "
        run: docker build -t ${{ secrets.DOKER_NAME}}/docker-image .
      - name: " pushing to docker hub "
        run: docker push ${{ secrets.DOKER_NAME}}/docker-image
